# Generated by Django 4.0.5 on 2022-09-21 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubriseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_order', models.CharField(blank=True, max_length=999, null=True)),
                ('status', models.CharField(blank=True, max_length=999, null=True)),
                ('service_type', models.CharField(blank=True, max_length=999, null=True)),
                ('email', models.CharField(blank=True, max_length=999, null=True)),
                ('first_name', models.CharField(blank=True, max_length=999, null=True)),
                ('last_name', models.CharField(blank=True, max_length=999, null=True)),
                ('phone', models.CharField(blank=True, max_length=999, null=True)),
                ('address_1', models.CharField(blank=True, max_length=999, null=True)),
                ('address_2', models.CharField(blank=True, max_length=999, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=999, null=True)),
                ('city', models.CharField(blank=True, max_length=999, null=True)),
                ('namePaiement', models.CharField(blank=True, max_length=999, null=True)),
                ('amount', models.CharField(blank=True, max_length=999, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=999)),
                ('expected_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('pictureplatform', models.CharField(blank=True, max_length=999)),
                ('statuscolor', models.CharField(blank=True, max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='HubriseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_order_item', models.CharField(blank=True, max_length=999, null=True)),
                ('product_name', models.CharField(blank=True, max_length=999, null=True)),
                ('priceProduct', models.CharField(blank=True, max_length=999, null=True)),
                ('quantityProduct', models.CharField(blank=True, max_length=999, null=True)),
                ('HubriseOrderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='popup.hubriseorder')),
            ],
        ),
        migrations.CreateModel(
            name='HubriseOrderItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_order_item_option', models.CharField(blank=True, max_length=999, null=True)),
                ('nameOption', models.CharField(blank=True, max_length=999, null=True)),
                ('priceOption', models.CharField(blank=True, max_length=999, null=True)),
                ('quantityOption', models.CharField(blank=True, max_length=999, null=True)),
                ('HubriseOrderItemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entriesoption', to='popup.hubriseorderitem')),
            ],
        ),
    ]
